"""
LoopSec Core Data Models

Shared data structures passed between agents in the pipeline.
Every agent reads from and writes to these models.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class FindingSource(str, Enum):
    SAST = "sast"           # Static analysis
    DAST = "dast"           # Dynamic / pentest
    SCA = "sca"             # Dependency scan
    SECRET = "secret"       # Secrets detection


class PatchStatus(str, Enum):
    PENDING = "pending"
    APPLIED = "applied"
    VERIFIED = "verified"
    FAILED = "failed"
    REGRESSED = "regressed"


class PipelineStatus(str, Enum):
    QUEUED = "queued"
    ANALYZING = "analyzing"
    DEPLOYING = "deploying"
    ATTACKING = "attacking"
    MAPPING = "mapping"
    FIXING = "fixing"
    VERIFYING = "verifying"
    COMPLETE = "complete"
    ERRORED = "errored"


# ---------------------------------------------------------------------------
# Core Models
# ---------------------------------------------------------------------------

class Finding(BaseModel):
    """A single vulnerability discovered by any agent."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    source: FindingSource
    severity: Severity
    title: str
    description: str
    cwe_id: str | None = None              # e.g. "CWE-79"
    owasp_category: str | None = None      # e.g. "A03:2021 Injection"

    # Location in source code (filled by Analyzer or Mapper)
    file_path: str | None = None
    line_start: int | None = None
    line_end: int | None = None
    function_name: str | None = None
    code_snippet: str | None = None

    # Location in running app (filled by Attacker)
    endpoint: str | None = None
    http_method: str | None = None
    parameter: str | None = None

    # Tool that found it
    tool: str | None = None                # e.g. "semgrep", "zap", "nuclei"
    rule_id: str | None = None             # e.g. "python.lang.security.audit.exec-used"
    raw_output: dict[str, Any] | None = None

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Exploit(BaseModel):
    """A proof-of-concept exploit generated by the Attacker agent."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    finding_id: str                         # Links to Finding
    description: str
    request: str                            # Raw HTTP request or command
    response_snippet: str | None = None     # Evidence of exploitation
    steps: list[str] = Field(default_factory=list)
    verified: bool = False


class Patch(BaseModel):
    """A code fix generated by the Fixer agent."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    finding_id: str
    file_path: str
    original_code: str
    patched_code: str
    diff: str                               # Unified diff
    explanation: str                         # LLM-generated explanation
    status: PatchStatus = PatchStatus.PENDING

    # Validation results
    passes_sast: bool | None = None         # Re-scan clean?
    passes_tests: bool | None = None        # App tests pass?
    exploit_mitigated: bool | None = None   # Verifier confirmed?


class MappedVulnerability(BaseModel):
    """A DAST finding mapped back to source code by the Mapper agent."""

    finding_id: str                         # The DAST Finding
    exploit_id: str | None = None           # The PoC Exploit
    file_path: str
    line_start: int
    line_end: int | None = None
    function_name: str | None = None
    confidence: float = 0.0                 # 0.0 - 1.0
    reasoning: str = ""                     # LLM explanation of the mapping


# ---------------------------------------------------------------------------
# Pipeline State — the central object passed through the entire pipeline
# ---------------------------------------------------------------------------

class ScanTarget(BaseModel):
    """What we're scanning."""

    repo_path: str                          # Local path to source code
    app_url: str | None = None              # URL of deployed/sandboxed app
    branch: str = "main"
    languages: list[str] = Field(default_factory=list)


class PipelineState(BaseModel):
    """
    The master state object that flows through the entire pipeline.
    Each agent reads what it needs and appends its results.
    """

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    status: PipelineStatus = PipelineStatus.QUEUED
    target: ScanTarget

    # Agent outputs
    findings: list[Finding] = Field(default_factory=list)
    exploits: list[Exploit] = Field(default_factory=list)
    mapped_vulnerabilities: list[MappedVulnerability] = Field(default_factory=list)
    patches: list[Patch] = Field(default_factory=list)

    # Verification results
    verified_fixes: list[str] = Field(default_factory=list)       # finding_ids confirmed fixed
    still_open: list[str] = Field(default_factory=list)           # finding_ids still exploitable
    regressions: list[str] = Field(default_factory=list)          # new issues from patches

    # Metadata
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: datetime | None = None
    errors: list[str] = Field(default_factory=list)

    # Container tracking
    sandbox_container_id: str | None = None

    def add_finding(self, finding: Finding) -> None:
        self.findings.append(finding)

    def add_exploit(self, exploit: Exploit) -> None:
        self.exploits.append(exploit)

    def add_patch(self, patch: Patch) -> None:
        self.patches.append(patch)

    def get_findings_by_severity(self, severity: Severity) -> list[Finding]:
        return [f for f in self.findings if f.severity == severity]

    def get_dast_findings(self) -> list[Finding]:
        return [f for f in self.findings if f.source == FindingSource.DAST]

    def get_sast_findings(self) -> list[Finding]:
        return [f for f in self.findings if f.source == FindingSource.SAST]

    def get_unfixed_findings(self) -> list[Finding]:
        fixed_ids = {p.finding_id for p in self.patches if p.status == PatchStatus.VERIFIED}
        return [f for f in self.findings if f.id not in fixed_ids]

    def summary(self) -> dict[str, Any]:
        return {
            "total_findings": len(self.findings),
            "by_severity": {
                s.value: len(self.get_findings_by_severity(s)) for s in Severity
            },
            "exploits_generated": len(self.exploits),
            "patches_generated": len(self.patches),
            "verified_fixes": len(self.verified_fixes),
            "still_open": len(self.still_open),
            "regressions": len(self.regressions),
        }
